### ISSUE TITLE
关于新建词表

### ISSUE THREAD

**Issue by Biajin-PKU** [Ethan-yt/guwenbert#10]
看到说明说是基于现代汉语的参数训练的，可词表是重新排序后更新的，请问这样也能work吗？

**Comment by Ethan-yt** [comment]
我们的词表用的是古文的词表。现代汉语只用Transformer层的权重，抛弃embedding层。第一阶段会重新学习embedding。


![](https://raw.githubusercontent.com/Ethan-yt/guwenbert/main/assets/pre-train-work-flow.png)

**Comment by ZJiaBin** [comment]
明白了！感谢大佬解答哈！

**Comment by Biajin-PKU** [comment]
明白了！感谢大佬解答！
