### ISSUE TITLE
请问能否公开一下古联杯的训练数据呢

### ISSUE THREAD

**Issue by AQA6666** [Ethan-yt/guwenbert#12]
刚刚搜索了一下，之前比赛报名时是可以公开下载训练数据集的，但是目前链接已经被重定向到别处了，请问您目前还保存有当时的训练集吗

**Comment by Ethan-yt** [comment]
Q: “古联杯”评测数据集可以公开吗？

A: 和主办方通过邮件询问了一下，主办方表示不能公开，如有需要可以联系zhucuiping@ancientbooks.cn
