### ISSUE TITLE
预训练模型的问题

### ISSUE THREAD

**Issue by JiaxinQin0814** [Ethan-yt/guwenbert#18]
你好，我在调用你的guwenbert-tf的时候  会给我报错 如图
![795c7cddecea5de7d833f6b7a61fd60](https://user-images.githubusercontent.com/82568786/189468244-c3375e58-3f5f-4363-b977-8a802adb9f86.jpg)

但是我用roberta的时候并不会

**Comment by Ethan-yt** [comment]
看起来像是segment embedding传了1.

**Comment by Ethan-yt** [comment]
https://github.com/Ethan-yt/guwenbert/issues/11
https://github.com/Ethan-yt/guwenbert/issues/13

**Comment by Ethan-yt** [comment]
<img width="946" alt="image" src="https://user-images.githubusercontent.com/9592150/189829096-2408dd08-9943-4ed6-b511-14d4d003709c.png">

**Comment by Ethan-yt** [comment]
这里直接用[SEP]分开就可以

**Comment by JiaxinQin0814** [comment]
sos,在哪里用[SEP]分开？
