### ISSUE TITLE
感觉效果不太好

### ISSUE THREAD

**Issue by wangbq18** [Ethan-yt/guwenbert#2]
fill-mask mask_token:
[CLS] 晋 太 元 中 ， 武 [MASK]人 捕 鱼 为 业 。 [SEP]

[CLS] 晋 太 元 中 ， 武 昌 人 捕 鱼 为 业 。 [SEP] 0.407
[CLS] 晋 太 元 中 ， 武 陵 人 捕 鱼 为 业 。 [SEP] 0.199
[CLS] 晋 太 元 中 ， 武 康 人 捕 鱼 为 业 。 [SEP] 0.147
[CLS] 晋 太 元 中 ， 武 进 人 捕 鱼 为 业 。 [SEP] 0.082
[CLS] 晋 太 元 中 ， 武 阳 人 捕 鱼 为 业 。 [SEP]

**Comment by Ethan-yt** [comment]
可能会出现一些badcase，我也不能保证所有case都是准确的，毕竟都是机器自己学的。。
评价效果好不好还需要靠数据集，如果有相关的开源数据集可以分享一下。
目前只在NER任务做了评测，其他任务还没试过

**Comment by wangbq18** [comment]
> 可能会出现一些badcase，我也不能保证所有case都是准确的，毕竟都是机器自己学的。。
> 评价效果好不好还需要靠数据集，如果有相关的开源数据集可以分享一下。
> 目前只在NER任务做了评测，其他任务还没试过

嗯，很棒的工作！

**Comment by Ethan-yt** [comment]
> > 可能会出现一些badcase，我也不能保证所有case都是准确的，毕竟都是机器自己学的。。
> > 评价效果好不好还需要靠数据集，如果有相关的开源数据集可以分享一下。
> > 目前只在NER任务做了评测，其他任务还没试过
> 
> 嗯，很棒的工作！

谢谢～本工作还需要在其他领域增加一些评测，主要是没有标准数据集，也没有一个可以和其他baseline模型公平对比的平台，希望未来这些会逐渐完善。
