### ISSUE TITLE
古联杯数据集发邮件询问官方人员，没回复怎么办呢

### ISSUE THREAD

**Issue by effort-yq** [Ethan-yt/guwenbert#22]

**Comment by Ethan-yt** [comment]
可能他们不开放了。先用公开的数据集吧。

**Comment by effort-yq** [comment]
好的，谢谢您




1486590231
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ethan-yt/guwenbert"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月8日(星期一) 下午3:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Ethan-yt/guwenbert] 古联杯数据集发邮件询问官方人员，没回复怎么办呢 (Issue #22)





 
可能他们不开放了。先用公开的数据集吧。
