### ISSUE TITLE
去停用词的问题

### ISSUE THREAD

**Issue by FrankFishman** [Ethan-yt/guwenbert#24]
在做红楼梦对话的情感分析的时候找到了您的文章，想问一下，您这个项目在分词时有没有进行去停用词处理，如果用到了，方便参考一下您的去停用词表嘛。（本人纯小白，刚上手nlp方向，有较多疑惑，望您多包涵）

**Comment by Ethan-yt** [comment]
没有考虑停用词

**Comment by FrankFishman** [comment]
好的，感谢
