### ISSUE TITLE
关于未来的工作计划

### ISSUE THREAD

**Issue by Ethan-yt** [Ethan-yt/guwenbert#5]
古文预训练模型真正的用途是下游任务的处理，目前这个repo只展示了语言模型和专名识别的结果，其中专名识别数据集按照主办方要求是不能公开的，所以未来的工作安排如下：

1. 根据不同的下游任务整理规范的、划分好的数据集。目前数据来源我只知道可以通过daizhige获取，如果有推荐的其他开放数据源可以回帖补充。整理标准的数据集对整个古文研究都有很大的推进作用，可以便于评测和对比不同的模型表现。
1. 断句任务。数据集可以通过移除标点生成。
1. 加注标点任务。数据集生成方式同上。
1. 书名识别任务。数据集通过抓取字典生成。

欢迎各位补充其他下游任务，注意任务必须是NLU类型任务，暂时不考虑生成式任务。

当然这些工作只有我一个人完成是比较困难的，欢迎有兴趣的朋友联系我，或者在Github留言，一起为促进古文研究的发展作出贡献。

**Comment by 131250208** [comment]
有兴趣做大藏经的标点和信息抽取，可以加微信交流一下吗？

**Comment by Ethan-yt** [comment]
> 有兴趣做大藏经的标点和信息抽取，可以加微信交流一下吗？

微信号邮件私发一下吧

**Comment by 131250208** [comment]
发你邮箱里了

**Comment by KuoChing-cmd** [comment]
你好，我对古文文本处理，很感兴趣，不过我水平一般😂

From Guoqing Zhang’s iPhone

On Feb 24, 2021, at 14:54, Andy Wong <notifications@github.com> wrote:

﻿

有兴趣做大藏经的标点和信息抽取，可以加微信交流一下吗？

**Comment by AQA6666** [comment]
请问可以开源一下您参加古联杯NER比赛的代码吗，想参考一下

**Comment by Ethan-yt** [comment]
参考新项目 https://github.com/Ethan-yt/CCLUE
