### ISSUE TITLE
预训练语料

### ISSUE THREAD

**Issue by neoql** [Ethan-yt/guwenbert#6]
问一下，
1.你在预训练阶段使用的什么语料？大概多大规模？
2.预训练时，阶段1和阶段2使用的是相同的语料吗？阶段1训练时是否掺入了现代汉语的语料？

**Comment by Ethan-yt** [comment]
GuwenBERT基于殆知阁古代文献语料训练，其中包含15,694本古文书籍，字符数1.7B。

两个阶段的语料、任务相同，唯一不同的只是第一阶段冻结了Transformer层，以便学习embeddings
