### ISSUE TITLE
想请教一下模型结构的问题，为什么模型权重从pooler层之后就没有了

### ISSUE THREAD

**Issue by cloudyskyy** [Ethan-yt/guwenbert#7]
我发现您的模型与原本的roberta模型相比，从pooler层之后就少了一些层（用于MLM训练的一些层）。由于我本人需要用tensorflow版的checkpoint，所以将您的checkpoint转化为了tensorflow版，（可以确保转换脚本没有问题）但是发现在pooler层后少了以下最后几层：
cls/predictions/output_bias (DT_FLOAT) [21128]
cls/predictions/transform/LayerNorm/beta (DT_FLOAT) [768]
cls/predictions/transform/LayerNorm/gamma (DT_FLOAT) [768]
cls/predictions/transform/dense/bias (DT_FLOAT) [768]
cls/predictions/transform/dense/kernel (DT_FLOAT) [768,768]
cls/seq_relationship/output_bias (DT_FLOAT) [2]
cls/seq_relationship/output_weights (DT_FLOAT) [2,768]
global_step (DT_INT64) []
所以当我load权重的时候报错：
tensorflow.python.framework.errors_impl.NotFoundError: Key cls/predictions/transform/dense/kernel not found in checkpoint
意思是'cls/'这几层在checkpoint里没有。这是为什么呢？为什么您的权重会从pooler层后就没有了。。我开始以为是我的转换脚本有问题，后来直接去读您的pytorch checkpoins发现最后也确实是只有pooler那两层：
pooler.dense.weight
pooler.dense.bias
pooler层后面就没有Roberta TensorFlow checkpoint 'cls/'这几层，导致我的模型加载不了TensorFlow checkpoint， 很难受。。为什么会没有呢， 按理说在做MLM预训练的时候这几层必然是要有的才对，我也需要接着您的权重做MLM训练。

**Comment by cloudyskyy** [comment]
好吧我好像解决了。我好像问了一个比较蠢的问题，我应该用RobertaForMaskedLM读权重，而不是用RobertaModel读权重。我对huggingface框架不太熟悉。。我的锅

**Comment by Ethan-yt** [comment]
是的，RobertaForMaskedLM才有lm head。感谢关注。

**Comment by Ethan-yt** [comment]
config.json里面的模型架构使用的就是RobertaForMaskedLM

**Comment by cloudyskyy** [comment]
> config.json里面的模型架构使用的就是RobertaForMaskedLM

谢谢回复~已经解决了
